### ISSUE TITLE
Windows 2022 - packer-windows-update-elevated.ps1 repeatedly fails

### ISSUE THREAD

**Issue by bronandrews** [rgl/packer-plugin-windows-update#142]
Hi,
I am using this plugin v0.15.0 to install updates during a fresh Windows 2022 build. 
I'm including Important updates only, with the following syntax.

```
provisioner "windows-update" {
      search_criteria = "AutoSelectOnWebSites=1 and IsInstalled=0"
      filters = [
         "include:$true"
      ]
}
```

It finds new Updates and seems to carry out the install, but consistently fails when trying to exit Windows Modules Installer...
sample output log looks like...

_2024/05/09 14:33:10 ui:     hyperv-iso.appbase: Waiting for the Windows Modules Installer to exit...
2024/05/09 14:33:56 ui:     hyperv-iso.appbase: Waiting for operation to complete (system performance: 4% cpu; 13% memory)...
memory)...
2024/05/09 14:41:05 ui:     hyperv-iso.appbase: Waiting for operation to complete (system performance: 1% cpu; 13% memory)...
2024/05/09 14:41:55 packer-plugin-hyperv_v1.1.3_x5.0_windows_amd64.exe plugin: 2024/05/09 14:41:55 [ERROR] Remote command exited with '1': PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1
2024/05/09 14:41:55 packer-plugin-hyperv_v1.1.3_x5.0_windows_amd64.exe plugin: 2024/05/09 14:41:55 [INFO] RPC endpoint: Communicator ended with: 1
2024/05/09 14:41:55 [INFO] 3047 bytes written for 'stdout'
2024/05/09 14:41:55 [INFO] 0 bytes written for 'stderr'
2024/05/09 14:41:55 [INFO] RPC client: Communicator ended with: 1
2024/05/09 14:41:55 [INFO] RPC endpoint: Communicator ended with: 1
2024/05/09 14:41:55 packer-plugin-windows-update_v0.15.0_x5.0_windows_amd64.exe plugin: 2024/05/09 14:41:55 [INFO] 0 bytes written for 'stderr'
2024/05/09 14:41:55 packer-plugin-windows-update_v0.15.0_x5.0_windows_amd64.exe plugin: 2024/05/09 14:41:55 [INFO] 3047 bytes written for 'stdout'
2024/05/09 14:41:55 packer-plugin-windows-update_v0.15.0_x5.0_windows_amd64.exe plugin: 2024/05/09 14:41:55 [INFO] RPC client: Communicator ended with: 1
2024/05/09 14:41:55 packer-plugin-windows-update_v0.15.0_x5.0_windows_amd64.exe plugin: 2024/05/09 14:41:55 Retryable error: Windows update script exited with non-zero exit status: 1_

As its "retryable" - it repeats this 4 more times, until :
**retry count exhausted. Last err: Windows update script exited with non-zero exit status**
then the packer process exits and server build is removed.

I've tried various things with repeating calls to the provisioner, and the **max_retries** setting.
When I manually restart the server while this is happening, it seems to break out of the deadlock and the packer process continues.
But that is not realistic when building a stack of new servers. 

Any suggestions about how to get over this issue? 
Looking back over Open issues, feels like this error has been a problem for a while.....will it be fixed?

Many thanks!

**Comment by bjmcdaniel** [comment]
Been having the same issue.  Looking for solutions.

**Comment by rvishalturaga** [comment]
Hi, I am facing a similar issue as well but for a Windows Server 2019 Datacenter VM. We are using Azure Image Builder and running the WindowsUpdate customizer. The packer-windows-update-elevated.ps1 script runs initially and then gives a non zero error. I observed a non zero exit code (101) after which the VM restarts. After the VM is back the same script is run after which I get the following error

PACKER 2024/07/18 13:43:29 ui error: ==> azure-arm: The argument 'C:/Windows/Temp/packer-windows-update-elevated.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
[83dbfb93-12a1-413f-a601-e186228f

**Comment by Raeykall** [comment]
Hi all, just to report I am seeing the same issue when attempting to use the Packer for Win11 Multi-Session

[5c307259-2810-456f-9b21-df1c667950ba] PACKER 2024/07/29 09:55:38 ui:     azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 190
[5c307259-2810-456f-9b21-df1c667950ba] PACKER 2024/07/29 09:55:38 ui:     azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1
[5c307259-2810-456f-9b21-df1c667950ba] PACKER 2024/07/29 09:55:38 ui:     azure-arm: ERROR EXCEPTION: System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.

**Comment by rvishalturaga** [comment]
Hi @Raeykall, Can you please share in detail on what the error code is? Maybe paste a bigger section of the customizations log? Maybe we can work together to understand the issue and resolve it. 

My expertise is based on Azure Image Builder only so I'm not sure to what level I can help but I want to contribute to how much ever I can. :)

**Comment by jonildoasantos** [comment]
Hi, I have a similar issue, but for Windows 11 Enterprise Multi-Session using Image Builder...

[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:02 ui: ==> azure-arm: Running Windows update...
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:02 packer-plugin-azure plugin: 2024/07/31 02:41:02 [INFO] starting remote command: PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:09 ui:     azure-arm: Searching for Windows updates...
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 packer-plugin-azure plugin: 2024/07/31 02:41:34 [INFO] command 'PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1' exited with code: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 packer-plugin-azure plugin: 2024/07/31 02:41:34 [INFO] RPC endpoint: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 [INFO] 0 bytes written for 'stderr'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 [INFO] 1100 bytes written for 'stdout'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 [INFO] RPC client: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 [INFO] RPC endpoint: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR: You cannot call a method on a null-valued expression.
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 packer-plugin-windows-update plugin: 2024/07/31 02:41:34 [INFO] 1100 bytes written for 'stdout'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 packer-plugin-windows-update plugin: 2024/07/31 02:41:34 [INFO] 0 bytes written for 'stderr'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 packer-plugin-windows-update plugin: 2024/07/31 02:41:34 [INFO] RPC client: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 190
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR EXCEPTION: System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR EXCEPTION:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 ui:     azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:34 packer-plugin-windows-update plugin: 2024/07/31 02:41:34 Retryable error: Windows update script exited with non-zero exit status: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:39 packer-plugin-azure plugin: 2024/07/31 02:41:39 [INFO] starting remote command: PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:45 ui:     azure-arm: Searching for Windows updates...
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 [INFO] 0 bytes written for 'stderr'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 packer-plugin-azure plugin: 2024/07/31 02:41:50 [INFO] command 'PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1' exited with code: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 packer-plugin-azure plugin: 2024/07/31 02:41:50 [INFO] RPC endpoint: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 [INFO] 1100 bytes written for 'stdout'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 [INFO] RPC client: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 ui:     azure-arm: ERROR: You cannot call a method on a null-valued expression.
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 [INFO] RPC endpoint: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 packer-plugin-windows-update plugin: 2024/07/31 02:41:50 [INFO] 1100 bytes written for 'stdout'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 packer-plugin-windows-update plugin: 2024/07/31 02:41:50 [INFO] 0 bytes written for 'stderr'
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 packer-plugin-windows-update plugin: 2024/07/31 02:41:50 [INFO] RPC client: Communicator ended with: 1
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 ui:     azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 190
[8a6c2380-c4f9-480c-a69a-9d0bd11f2f17] PACKER 2024/07/31 02:41:50 ui:     azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1

**Comment by pvess** [comment]
Any update on this issue from someone?

**Comment by ricardofalc** [comment]
> Any update on this issue from someone?

Have you tried the options given here?
https://github.com/rgl/packer-plugin-windows-update/issues/144
https://learn.microsoft.com/en-us/windows/release-health/status-windows-11-23H2#3351msgdesc

**Comment by saily** [comment]
Hi @bronandrews, it took me a while to get this fixed, but it seems the provisioner does not work properly if you override the default shell for `openssh` which I did. 

I've set the default shell to `powershell` using a registry entry as shown below. This caused failures without a clear reason. 

```ps1
# FIXME: This causes failure with windows-update provisioner, so disabled it!
New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force
```

Hope this helps and @rgl requesting your input if this could be valid reason.

**Comment by bronandrews** [comment]
Hi @saily 
Many thanks for your update - I've just been testing this again...

As before, I'm using packer to provision a Hyper-V VM from a Windows2022 ISO image 
[(https://developer.hashicorp.com/packer/integrations/hashicorp/hyperv/latest/components/builder/iso)]

This time I'm using the most recent `windows-update` plugin version (0.16.7)  
and I can confirm I was already setting the default shell the powershell, as per your fix - this gets done via a script that gets called on first login to the machine...

But still getting the same error, still consistently fails when exiting the installer
and it retries 4 times until  `retry count exhausted. Last err: Windows update script exited with non-zero exit status`

Any other ideas?

**Comment by bronandrews** [comment]
Hi again @saily 
Apologies - on reflection, I think I misunderstood your fix, 
you're suggesting NOT to change the default shell to powershell?  As latest until the Windows updates are complete?

I'll will try to change the default later in the process & revert

**Comment by username-is-already-taken2** [comment]
@saily - Hi there, I just wanted to thank you for your suggestion about not changing the default shell.  I've been struggling for days!! trying to get windows 2025 patched and it wouldn't get past the cumulative update.   Thank you

**Comment by mrodriguezfx** [comment]
@saily - Same thing here i removed the openssh default shell registry key and it started working on windows server 2016/2019/2022.

**Comment by bronandrews** [comment]
I'm not in a position to test this again, but happy to close off the issue if others feel this is a fix to the issue.
Thanks all
